package nico.kittylib.api.util;

import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.item.Item;
import net.minecraft.item.Items;
import net.minecraft.util.DyeColor;
import nico.kittylib.api.java.MapBuilder;

import java.util.Map;

public class KittyLibDyeUtil {
    public static final Map<DyeColor, Block> WOOL_BLOCKS = new MapBuilder<DyeColor, Block>()
            .put(DyeColor.WHITE, Blocks.WHITE_WOOL)
            .put(DyeColor.ORANGE, Blocks.ORANGE_WOOL)
            .put(DyeColor.MAGENTA, Blocks.MAGENTA_WOOL)
            .put(DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_WOOL)
            .put(DyeColor.YELLOW, Blocks.YELLOW_WOOL)
            .put(DyeColor.LIME, Blocks.LIME_WOOL)
            .put(DyeColor.PINK, Blocks.PINK_WOOL)
            .put(DyeColor.GRAY, Blocks.GRAY_WOOL)
            .put(DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_WOOL)
            .put(DyeColor.CYAN, Blocks.CYAN_WOOL)
            .put(DyeColor.PURPLE, Blocks.PURPLE_WOOL)
            .put(DyeColor.BLUE, Blocks.BLUE_WOOL)
            .put(DyeColor.BROWN, Blocks.BROWN_WOOL)
            .put(DyeColor.GREEN, Blocks.GREEN_WOOL)
            .put(DyeColor.RED, Blocks.RED_WOOL)
            .put(DyeColor.BLACK, Blocks.BLACK_WOOL)
            .build();

    public static final Map<DyeColor, Block> CARPET_BLOCKS = new MapBuilder<DyeColor, Block>()
            .put(DyeColor.WHITE, Blocks.WHITE_CARPET)
            .put(DyeColor.ORANGE, Blocks.ORANGE_CARPET)
            .put(DyeColor.MAGENTA, Blocks.MAGENTA_CARPET)
            .put(DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_CARPET)
            .put(DyeColor.YELLOW, Blocks.YELLOW_CARPET)
            .put(DyeColor.LIME, Blocks.LIME_CARPET)
            .put(DyeColor.PINK, Blocks.PINK_CARPET)
            .put(DyeColor.GRAY, Blocks.GRAY_CARPET)
            .put(DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_CARPET)
            .put(DyeColor.CYAN, Blocks.CYAN_CARPET)
            .put(DyeColor.PURPLE, Blocks.PURPLE_CARPET)
            .put(DyeColor.BLUE, Blocks.BLUE_CARPET)
            .put(DyeColor.BROWN, Blocks.BROWN_CARPET)
            .put(DyeColor.GREEN, Blocks.GREEN_CARPET)
            .put(DyeColor.RED, Blocks.RED_CARPET)
            .put(DyeColor.BLACK, Blocks.BLACK_CARPET)
            .build();

    public static final Map<DyeColor, Block> TERRACOTTA_BLOCKS = new MapBuilder<DyeColor, Block>()
            .put(DyeColor.WHITE, Blocks.WHITE_TERRACOTTA)
            .put(DyeColor.ORANGE, Blocks.ORANGE_TERRACOTTA)
            .put(DyeColor.MAGENTA, Blocks.MAGENTA_TERRACOTTA)
            .put(DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_TERRACOTTA)
            .put(DyeColor.YELLOW, Blocks.YELLOW_TERRACOTTA)
            .put(DyeColor.LIME, Blocks.LIME_TERRACOTTA)
            .put(DyeColor.PINK, Blocks.PINK_TERRACOTTA)
            .put(DyeColor.GRAY, Blocks.GRAY_TERRACOTTA)
            .put(DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_TERRACOTTA)
            .put(DyeColor.CYAN, Blocks.CYAN_TERRACOTTA)
            .put(DyeColor.PURPLE, Blocks.PURPLE_TERRACOTTA)
            .put(DyeColor.BLUE, Blocks.BLUE_TERRACOTTA)
            .put(DyeColor.BROWN, Blocks.BROWN_TERRACOTTA)
            .put(DyeColor.GREEN, Blocks.GREEN_TERRACOTTA)
            .put(DyeColor.RED, Blocks.RED_TERRACOTTA)
            .put(DyeColor.BLACK, Blocks.BLACK_TERRACOTTA)
            .build();

    public static final Map<DyeColor, Block> GLAZED_TERRACOTTA_BLOCKS = new MapBuilder<DyeColor, Block>()
            .put(DyeColor.WHITE, Blocks.WHITE_GLAZED_TERRACOTTA)
            .put(DyeColor.ORANGE, Blocks.ORANGE_GLAZED_TERRACOTTA)
            .put(DyeColor.MAGENTA, Blocks.MAGENTA_GLAZED_TERRACOTTA)
            .put(DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA)
            .put(DyeColor.YELLOW, Blocks.YELLOW_GLAZED_TERRACOTTA)
            .put(DyeColor.LIME, Blocks.LIME_GLAZED_TERRACOTTA)
            .put(DyeColor.PINK, Blocks.PINK_GLAZED_TERRACOTTA)
            .put(DyeColor.GRAY, Blocks.GRAY_GLAZED_TERRACOTTA)
            .put(DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA)
            .put(DyeColor.CYAN, Blocks.CYAN_GLAZED_TERRACOTTA)
            .put(DyeColor.PURPLE, Blocks.PURPLE_GLAZED_TERRACOTTA)
            .put(DyeColor.BLUE, Blocks.BLUE_GLAZED_TERRACOTTA)
            .put(DyeColor.BROWN, Blocks.BROWN_GLAZED_TERRACOTTA)
            .put(DyeColor.GREEN, Blocks.GREEN_GLAZED_TERRACOTTA)
            .put(DyeColor.RED, Blocks.RED_GLAZED_TERRACOTTA)
            .put(DyeColor.BLACK, Blocks.BLACK_GLAZED_TERRACOTTA)
            .build();

    public static final Map<DyeColor, Block> BED_BLOCKS = new MapBuilder<DyeColor, Block>()
            .put(DyeColor.WHITE, Blocks.WHITE_BED)
            .put(DyeColor.ORANGE, Blocks.ORANGE_BED)
            .put(DyeColor.MAGENTA, Blocks.MAGENTA_BED)
            .put(DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_BED)
            .put(DyeColor.YELLOW, Blocks.YELLOW_BED)
            .put(DyeColor.LIME, Blocks.LIME_BED)
            .put(DyeColor.PINK, Blocks.PINK_BED)
            .put(DyeColor.GRAY, Blocks.GRAY_BED)
            .put(DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_BED)
            .put(DyeColor.CYAN, Blocks.CYAN_BED)
            .put(DyeColor.PURPLE, Blocks.PURPLE_BED)
            .put(DyeColor.BLUE, Blocks.BLUE_BED)
            .put(DyeColor.BROWN, Blocks.BROWN_BED)
            .put(DyeColor.GREEN, Blocks.GREEN_BED)
            .put(DyeColor.RED, Blocks.RED_BED)
            .put(DyeColor.BLACK, Blocks.BLACK_BED)
            .build();

    public static final Map<DyeColor, Block> STAINED_GLASS_BLOCKS = new MapBuilder<DyeColor, Block>()
            .put(DyeColor.WHITE, Blocks.WHITE_STAINED_GLASS)
            .put(DyeColor.ORANGE, Blocks.ORANGE_STAINED_GLASS)
            .put(DyeColor.MAGENTA, Blocks.MAGENTA_STAINED_GLASS)
            .put(DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_STAINED_GLASS)
            .put(DyeColor.YELLOW, Blocks.YELLOW_STAINED_GLASS)
            .put(DyeColor.LIME, Blocks.LIME_STAINED_GLASS)
            .put(DyeColor.PINK, Blocks.PINK_STAINED_GLASS)
            .put(DyeColor.GRAY, Blocks.GRAY_STAINED_GLASS)
            .put(DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_STAINED_GLASS)
            .put(DyeColor.CYAN, Blocks.CYAN_STAINED_GLASS)
            .put(DyeColor.PURPLE, Blocks.PURPLE_STAINED_GLASS)
            .put(DyeColor.BLUE, Blocks.BLUE_STAINED_GLASS)
            .put(DyeColor.BROWN, Blocks.BROWN_STAINED_GLASS)
            .put(DyeColor.GREEN, Blocks.GREEN_STAINED_GLASS)
            .put(DyeColor.RED, Blocks.RED_STAINED_GLASS)
            .put(DyeColor.BLACK, Blocks.BLACK_STAINED_GLASS)
            .build();

    public static final Map<DyeColor, Block> STAINED_GLASS_PANE_BLOCKS = new MapBuilder<DyeColor, Block>()
            .put(DyeColor.WHITE, Blocks.WHITE_STAINED_GLASS_PANE)
            .put(DyeColor.ORANGE, Blocks.ORANGE_STAINED_GLASS_PANE)
            .put(DyeColor.MAGENTA, Blocks.MAGENTA_STAINED_GLASS_PANE)
            .put(DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_STAINED_GLASS_PANE)
            .put(DyeColor.YELLOW, Blocks.YELLOW_STAINED_GLASS_PANE)
            .put(DyeColor.LIME, Blocks.LIME_STAINED_GLASS_PANE)
            .put(DyeColor.PINK, Blocks.PINK_STAINED_GLASS_PANE)
            .put(DyeColor.GRAY, Blocks.GRAY_STAINED_GLASS_PANE)
            .put(DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_STAINED_GLASS_PANE)
            .put(DyeColor.CYAN, Blocks.CYAN_STAINED_GLASS_PANE)
            .put(DyeColor.PURPLE, Blocks.PURPLE_STAINED_GLASS_PANE)
            .put(DyeColor.BLUE, Blocks.BLUE_STAINED_GLASS_PANE)
            .put(DyeColor.BROWN, Blocks.BROWN_STAINED_GLASS_PANE)
            .put(DyeColor.GREEN, Blocks.GREEN_STAINED_GLASS_PANE)
            .put(DyeColor.RED, Blocks.RED_STAINED_GLASS_PANE)
            .put(DyeColor.BLACK, Blocks.BLACK_STAINED_GLASS_PANE)
            .build();

    public static final Map<DyeColor, Block> CONCRETE_BLOCKS = new MapBuilder<DyeColor, Block>()
            .put(DyeColor.WHITE, Blocks.WHITE_CONCRETE)
            .put(DyeColor.ORANGE, Blocks.ORANGE_CONCRETE)
            .put(DyeColor.MAGENTA, Blocks.MAGENTA_CONCRETE)
            .put(DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_CONCRETE)
            .put(DyeColor.YELLOW, Blocks.YELLOW_CONCRETE)
            .put(DyeColor.LIME, Blocks.LIME_CONCRETE)
            .put(DyeColor.PINK, Blocks.PINK_CONCRETE)
            .put(DyeColor.GRAY, Blocks.GRAY_CONCRETE)
            .put(DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_CONCRETE)
            .put(DyeColor.CYAN, Blocks.CYAN_CONCRETE)
            .put(DyeColor.PURPLE, Blocks.PURPLE_CONCRETE)
            .put(DyeColor.BLUE, Blocks.BLUE_CONCRETE)
            .put(DyeColor.BROWN, Blocks.BROWN_CONCRETE)
            .put(DyeColor.GREEN, Blocks.GREEN_CONCRETE)
            .put(DyeColor.RED, Blocks.RED_CONCRETE)
            .put(DyeColor.BLACK, Blocks.BLACK_CONCRETE)
            .build();

    public static final Map<DyeColor, Block> CONCRETE_POWDER_BLOCKS = new MapBuilder<DyeColor, Block>()
            .put(DyeColor.WHITE, Blocks.WHITE_CONCRETE_POWDER)
            .put(DyeColor.ORANGE, Blocks.ORANGE_CONCRETE_POWDER)
            .put(DyeColor.MAGENTA, Blocks.MAGENTA_CONCRETE_POWDER)
            .put(DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_CONCRETE_POWDER)
            .put(DyeColor.YELLOW, Blocks.YELLOW_CONCRETE_POWDER)
            .put(DyeColor.LIME, Blocks.LIME_CONCRETE_POWDER)
            .put(DyeColor.PINK, Blocks.PINK_CONCRETE_POWDER)
            .put(DyeColor.GRAY, Blocks.GRAY_CONCRETE_POWDER)
            .put(DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_CONCRETE_POWDER)
            .put(DyeColor.CYAN, Blocks.CYAN_CONCRETE_POWDER)
            .put(DyeColor.PURPLE, Blocks.PURPLE_CONCRETE_POWDER)
            .put(DyeColor.BLUE, Blocks.BLUE_CONCRETE_POWDER)
            .put(DyeColor.BROWN, Blocks.BROWN_CONCRETE_POWDER)
            .put(DyeColor.GREEN, Blocks.GREEN_CONCRETE_POWDER)
            .put(DyeColor.RED, Blocks.RED_CONCRETE_POWDER)
            .put(DyeColor.BLACK, Blocks.BLACK_CONCRETE_POWDER)
            .build();

    public static final Map<DyeColor, Block> BANNER_BLOCKS = new MapBuilder<DyeColor, Block>()
            .put(DyeColor.WHITE, Blocks.WHITE_BANNER)
            .put(DyeColor.ORANGE, Blocks.ORANGE_BANNER)
            .put(DyeColor.MAGENTA, Blocks.MAGENTA_BANNER)
            .put(DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_BANNER)
            .put(DyeColor.YELLOW, Blocks.YELLOW_BANNER)
            .put(DyeColor.LIME, Blocks.LIME_BANNER)
            .put(DyeColor.PINK, Blocks.PINK_BANNER)
            .put(DyeColor.GRAY, Blocks.GRAY_BANNER)
            .put(DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_BANNER)
            .put(DyeColor.CYAN, Blocks.CYAN_BANNER)
            .put(DyeColor.PURPLE, Blocks.PURPLE_BANNER)
            .put(DyeColor.BLUE, Blocks.BLUE_BANNER)
            .put(DyeColor.BROWN, Blocks.BROWN_BANNER)
            .put(DyeColor.GREEN, Blocks.GREEN_BANNER)
            .put(DyeColor.RED, Blocks.RED_BANNER)
            .put(DyeColor.BLACK, Blocks.BLACK_BANNER)
            .build();

    public static final Map<DyeColor, Block> SHULKER_BOX_BLOCKS = new MapBuilder<DyeColor, Block>()
            .put(DyeColor.WHITE, Blocks.WHITE_SHULKER_BOX)
            .put(DyeColor.ORANGE, Blocks.ORANGE_SHULKER_BOX)
            .put(DyeColor.MAGENTA, Blocks.MAGENTA_SHULKER_BOX)
            .put(DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_SHULKER_BOX)
            .put(DyeColor.YELLOW, Blocks.YELLOW_SHULKER_BOX)
            .put(DyeColor.LIME, Blocks.LIME_SHULKER_BOX)
            .put(DyeColor.PINK, Blocks.PINK_SHULKER_BOX)
            .put(DyeColor.GRAY, Blocks.GRAY_SHULKER_BOX)
            .put(DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_SHULKER_BOX)
            .put(DyeColor.CYAN, Blocks.CYAN_SHULKER_BOX)
            .put(DyeColor.PURPLE, Blocks.PURPLE_SHULKER_BOX)
            .put(DyeColor.BLUE, Blocks.BLUE_SHULKER_BOX)
            .put(DyeColor.BROWN, Blocks.BROWN_SHULKER_BOX)
            .put(DyeColor.GREEN, Blocks.GREEN_SHULKER_BOX)
            .put(DyeColor.RED, Blocks.RED_SHULKER_BOX)
            .put(DyeColor.BLACK, Blocks.BLACK_SHULKER_BOX)
            .build();

    public static final Map<DyeColor, Block> CANDLE_BLOCKS = new MapBuilder<DyeColor, Block>()
            .put(DyeColor.WHITE, Blocks.WHITE_CANDLE)
            .put(DyeColor.ORANGE, Blocks.ORANGE_CANDLE)
            .put(DyeColor.MAGENTA, Blocks.MAGENTA_CANDLE)
            .put(DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_CANDLE)
            .put(DyeColor.YELLOW, Blocks.YELLOW_CANDLE)
            .put(DyeColor.LIME, Blocks.LIME_CANDLE)
            .put(DyeColor.PINK, Blocks.PINK_CANDLE)
            .put(DyeColor.GRAY, Blocks.GRAY_CANDLE)
            .put(DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_CANDLE)
            .put(DyeColor.CYAN, Blocks.CYAN_CANDLE)
            .put(DyeColor.PURPLE, Blocks.PURPLE_CANDLE)
            .put(DyeColor.BLUE, Blocks.BLUE_CANDLE)
            .put(DyeColor.BROWN, Blocks.BROWN_CANDLE)
            .put(DyeColor.GREEN, Blocks.GREEN_CANDLE)
            .put(DyeColor.RED, Blocks.RED_CANDLE)
            .put(DyeColor.BLACK, Blocks.BLACK_CANDLE)
            .build();

    public static final Map<DyeColor, Block> CANDLE_CAKE_BLOCKS = new MapBuilder<DyeColor, Block>()
            .put(DyeColor.WHITE, Blocks.WHITE_CANDLE_CAKE)
            .put(DyeColor.ORANGE, Blocks.ORANGE_CANDLE_CAKE)
            .put(DyeColor.MAGENTA, Blocks.MAGENTA_CANDLE_CAKE)
            .put(DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_CANDLE_CAKE)
            .put(DyeColor.YELLOW, Blocks.YELLOW_CANDLE_CAKE)
            .put(DyeColor.LIME, Blocks.LIME_CANDLE_CAKE)
            .put(DyeColor.PINK, Blocks.PINK_CANDLE_CAKE)
            .put(DyeColor.GRAY, Blocks.GRAY_CANDLE_CAKE)
            .put(DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_CANDLE_CAKE)
            .put(DyeColor.CYAN, Blocks.CYAN_CANDLE_CAKE)
            .put(DyeColor.PURPLE, Blocks.PURPLE_CANDLE_CAKE)
            .put(DyeColor.BLUE, Blocks.BLUE_CANDLE_CAKE)
            .put(DyeColor.BROWN, Blocks.BROWN_CANDLE_CAKE)
            .put(DyeColor.GREEN, Blocks.GREEN_CANDLE_CAKE)
            .put(DyeColor.RED, Blocks.RED_CANDLE_CAKE)
            .put(DyeColor.BLACK, Blocks.BLACK_CANDLE_CAKE)
            .build();

    public static final Map<DyeColor, Item> DYE_ITEMS = new MapBuilder<DyeColor, Item>()
            .put(DyeColor.WHITE, Items.WHITE_DYE)
            .put(DyeColor.ORANGE, Items.ORANGE_DYE)
            .put(DyeColor.MAGENTA, Items.MAGENTA_DYE)
            .put(DyeColor.LIGHT_BLUE, Items.LIGHT_BLUE_DYE)
            .put(DyeColor.YELLOW, Items.YELLOW_DYE)
            .put(DyeColor.LIME, Items.LIME_DYE)
            .put(DyeColor.PINK, Items.PINK_DYE)
            .put(DyeColor.GRAY, Items.GRAY_DYE)
            .put(DyeColor.LIGHT_GRAY, Items.LIGHT_GRAY_DYE)
            .put(DyeColor.CYAN, Items.CYAN_DYE)
            .put(DyeColor.PURPLE, Items.PURPLE_DYE)
            .put(DyeColor.BLUE, Items.BLUE_DYE)
            .put(DyeColor.BROWN, Items.BROWN_DYE)
            .put(DyeColor.GREEN, Items.GREEN_DYE)
            .put(DyeColor.RED, Items.RED_DYE)
            .put(DyeColor.BLACK, Items.BLACK_DYE)
            .build();
}
